// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcRp2aUi3UIdyv_588I2Wrtf45dyl5UBM',
    appId: '1:40829503731:android:5e9cf5400a32ce03830f86',
    messagingSenderId: '40829503731',
    projectId: 'shoppingapp-54432',
    storageBucket: 'shoppingapp-54432.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtCLdGqXZkZD46zLwJzh0lMp5vGpG0s6g',
    appId: '1:40829503731:ios:dec682aa759c86a7830f86',
    messagingSenderId: '40829503731',
    projectId: 'shoppingapp-54432',
    storageBucket: 'shoppingapp-54432.firebasestorage.app',
    androidClientId: '40829503731-onq0vh3kkks5gl3gcai4roddjbvv043h.apps.googleusercontent.com',
    iosClientId: '40829503731-2ldmnu15drf11mf8636tuka48ptrv4h9.apps.googleusercontent.com',
    iosBundleId: 'com.commerce.eCommerce',
  );

}